# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  cpython:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . -r requirements_dev.txt

      - name: Run tests
        run: |
          python -m pytest

      - name: Run flake8
        run: |
          python -m flake8 aiogram_dialog

      - name: Run tests
        run: |
          pytest

      - name: Run vulture
        run: |
          python -m vulture aiogram_dialog --min-confidence 70
